spring:
  application:
    name: feed-processor
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false   # Instant → ISO-8601 string
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080

logging:
  level:
    com.sporty.feed: DEBUG
    
